import React,{useMemo,useState} from 'react'
import{createRoot}from'react-dom/client'
import{LayoutDashboard,WalletCards,CreditCard,ArrowDownLeft,ArrowUpRight,Users,Settings,FileText,Plus,Menu,X,ShieldCheck,CalendarDays,ChevronDown,Pencil,Trash2,ArrowLeft,Paperclip,Eye}from'lucide-react'
import'./styles.css'

const seedAccounts=[
{id:1,name:'Conta Principal',bank:'Santander',balance:48500,cardName:'Cartão Principal'},
{id:2,name:'Conta Reserva 1',bank:'Santander',balance:8300,cardName:'Cartão Reserva 1'},
{id:3,name:'Conta Reserva 2',bank:'Santander',balance:2140,cardName:'Cartão Reserva 2'},
{id:4,name:'Conta Reserva 3',bank:'Santander',balance:960,cardName:'Cartão Reserva 3'}]
const seedMovements=[
{id:1,account:1,date:'2026-09-14',type:'Entrada',description:'Aporte recebido',value:12000,reference:'Pagamento de contas',receipt:null},
{id:2,account:1,date:'2026-09-14',type:'Saída',description:'Devolução de saldo',value:3500,reference:'Sobra do aporte',receipt:null},
{id:3,account:1,date:'2026-09-13',type:'Saída',description:'Transferência para pagamento',value:2800,reference:'Contas',receipt:null},
{id:4,account:1,date:'2026-09-10',type:'Entrada',description:'Reposição',value:5000,reference:'Complemento',receipt:null},
{id:5,account:2,date:'2026-09-12',type:'Entrada',description:'Aporte recebido',value:4000,reference:'Reposição',receipt:null},
{id:6,account:3,date:'2026-08-29',type:'Saída',description:'Pagamento',value:850,reference:'Conta',receipt:null}]
const seedPurchases=[
{id:1,account:1,date:'2026-09-14',description:'Compra de material',value:1280},
{id:2,account:1,date:'2026-09-12',description:'Serviço',value:2150},
{id:3,account:1,date:'2026-09-05',description:'Despesa operacional',value:980.4},
{id:4,account:2,date:'2026-09-10',description:'Compra',value:420},
{id:5,account:3,date:'2026-08-22',description:'Compra',value:690.9},
{id:6,account:4,date:'2026-07-18',description:'Compra',value:315.5}]
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)
const dateBR=v=>new Intl.DateTimeFormat('pt-BR').format(new Date(v+'T12:00:00'))
function matches(date,period,year){const d=new Date(date+'T12:00:00');if(d.getFullYear()!=year)return false;if(period==='Todos')return true;if(period==='Hoje')return date==='2026-09-14';if(period==='Mês')return d.getMonth()===8; if(period==='Semana'){const n=new Date('2026-09-14T12:00:00');const day=n.getDay()||7;const start=new Date(n);start.setDate(n.getDate()-day+1);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+6);return d>=start&&d<=end}return true}

function App(){
const[page,setPage]=useState('dashboard'),[accounts,setAccounts]=useState(seedAccounts),[movements,setMovements]=useState(seedMovements),[purchases]=useState(seedPurchases),[selected,setSelected]=useState(1),[year,setYear]=useState('2026'),[period,setPeriod]=useState('Todos'),[mobile,setMobile]=useState(false),[modal,setModal]=useState(null),[editing,setEditing]=useState(null),[confirm,setConfirm]=useState(null),[notice,setNotice]=useState('')
const account=accounts.find(a=>a.id===selected)
const filteredMovements=useMemo(()=>movements.filter(m=>matches(m.date,period,year)),[movements,period,year])
const filteredPurchases=useMemo(()=>purchases.filter(p=>matches(p.date,period,year)),[purchases,period,year])
const filteredAccounts=period==='Todos'?accounts:accounts.filter(a=>filteredMovements.some(m=>m.account===a.id)||filteredPurchases.some(p=>p.account===a.id))
const totalBalance=filteredAccounts.reduce((s,a)=>s+a.balance,0)
const cardTotal=filteredPurchases.reduce((s,p)=>s+p.value,0)
function notify(t){setNotice(t);setTimeout(()=>setNotice(''),2200)}
function go(p){setPage(p);setMobile(false)}
function saveAccount(e){e.preventDefault();const f=new FormData(e.currentTarget);const a={id:Date.now(),name:f.get('name').trim(),bank:f.get('bank').trim(),balance:Number(f.get('balance')||0),cardName:f.get('cardName').trim()||'Cartão'};setAccounts(x=>[...x,a]);setSelected(a.id);setModal(null);notify('Conta criada com sucesso.')}
function removeAccount(id){setAccounts(x=>x.filter(a=>a.id!==id));setMovements(x=>x.filter(m=>m.account!==id));if(selected===id){const r=accounts.filter(a=>a.id!==id);setSelected(r[0]?.id||null)}setConfirm(null);notify('Conta excluída.')}
function saveMovement(e){e.preventDefault();const f=new FormData(e.currentTarget),type=f.get('type'),value=Number(f.get('value')),aid=Number(f.get('account')),date=f.get('date'),description=f.get('description').trim(),reference=f.get('reference').trim(),file=f.get('receipt');if(!value||!date||!description||!reference)return;const receipt=file?.size?{name:file.name,size:file.size}:editing?.receipt||null
if(editing){setAccounts(prev=>prev.map(a=>{let delta=0;if(a.id===editing.account)delta-=(editing.type==='Entrada'?editing.value:-editing.value);if(a.id===aid)delta+=(type==='Entrada'?value:-value);return delta?{...a,balance:a.balance+delta}:a}));setMovements(prev=>prev.map(m=>m.id===editing.id?{...m,account:aid,date,type,value,description,reference,receipt}:m));notify('Movimentação atualizada.')}else{setAccounts(prev=>prev.map(a=>a.id===aid?{...a,balance:a.balance+(type==='Entrada'?value:-value)}:a));setMovements(prev=>[{id:Date.now(),account:aid,date,type,value,description,reference,receipt},...prev]);notify('Movimentação registrada.')}setModal(null);setEditing(null)}
const nav=[['dashboard','Visão geral',LayoutDashboard],['accounts','Contas',WalletCards],['cards','Cartões de crédito',CreditCard],['movements','Movimentações',ArrowDownLeft],['receipts','Comprovantes',FileText],['users','Usuários e permissões',Users],['settings','Configurações',Settings]]
return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark">CF</div><div><strong>Central Financeira</strong><span>Controle financeiro</span></div><button className="icon mobile-close" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([k,l,I])=><button key={k} className={page===k?'nav active':'nav'} onClick={()=>go(k)}><I size={19}/><span>{l}</span></button>)}</nav><div className="admin"><ShieldCheck size={18}/><div><b>Administrador</b><small>Acesso completo</small></div></div></aside>
<main><header><button className="icon menu" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{nav.find(n=>n[0]===page)?.[1]}</h1><p>Controle centralizado das suas contas</p></div><button className="user-chip">Administrador <ChevronDown size={16}/></button></header>
{page==='dashboard'&&<section className="content"><div className="toolbar"><div className="filters"><CalendarDays size={17}/><select value={year} onChange={e=>setYear(e.target.value)}><option>2026</option><option>2025</option></select>{['Todos','Mês','Semana','Hoje'].map(p=><button key={p} className={period===p?'filter active':'filter'} onClick={()=>setPeriod(p)}>{p}</button>)}</div><button className="primary" onClick={()=>{setEditing(null);setModal('movement')}}><Plus size={18}/> Nova movimentação</button></div><div className="cards"><div className="stat"><span>Saldo total controlado</span><strong>{money(totalBalance)}</strong><small>Contas dentro do filtro</small></div><div className="stat"><span>Fatura dos cartões</span><strong>{money(cardTotal)}</strong><small>Compras dentro do filtro</small></div><div className="stat"><span>Contas cadastradas</span><strong>{filteredAccounts.length}</strong><small>Contas dentro do filtro</small></div><div className="stat"><span>Movimentações filtradas</span><strong>{filteredMovements.length}</strong><small>Período: {period}</small></div></div><div className="grid"><div className="panel"><div className="panel-head"><div><h2>Movimentações recentes</h2><p>Conta selecionada e período filtrado</p></div><select value={selected||''} onChange={e=>setSelected(Number(e.target.value))}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><Table rows={movements.filter(m=>m.account===selected&&matches(m.date,period,year))} edit={m=>{setEditing(m);setModal('movement')}}/></div><div className="panel"><div className="panel-head"><div><h2>Contas</h2><p>Saldo atual</p></div></div>{accounts.map(a=><button className="account-row" key={a.id} onClick={()=>{setSelected(a.id);go('accounts')}}><span className="bank-icon">S</span><div><b>{a.name}</b><small>{a.bank}</small></div><strong>{money(a.balance)}</strong></button>)}</div></div></section>}
{page==='accounts'&&<section className="content"><div className="toolbar"><div><h2>Contas cadastradas</h2><p>Você pode cadastrar quantas contas forem necessárias.</p></div><button className="primary" onClick={()=>setModal('account')}><Plus size={18}/> Nova conta</button></div><div className="account-grid">{accounts.map(a=><div className="account-card" key={a.id}><div className="account-title"><span className="bank-icon">S</span><div><h3>{a.name}</h3><p>{a.bank}</p></div></div><span className="label">Saldo atual</span><strong>{money(a.balance)}</strong><div className="card-actions"><button className="secondary" onClick={()=>{setSelected(a.id);go('movements')}}>Ver movimentações</button><button className="danger" onClick={()=>setConfirm(a)}><Trash2 size={15}/> Excluir</button></div></div>)}</div></section>}
{page==='movements'&&<section className="content"><div className="toolbar"><div><button className="back-button" onClick={()=>go('accounts')}><ArrowLeft size={16}/> Voltar</button><h2>{account?.name||'Movimentações'}</h2><p>Entradas e saídas da conta selecionada.</p></div><button className="primary" onClick={()=>{setEditing(null);setModal('movement')}}><Plus size={18}/> Nova movimentação</button></div><div className="panel"><div className="filter-line"><CalendarDays size={17}/><select value={year} onChange={e=>setYear(e.target.value)}><option>2026</option><option>2025</option></select>{['Todos','Mês','Semana','Hoje'].map(p=><button key={p} className={period===p?'filter active':'filter'} onClick={()=>setPeriod(p)}>{p}</button>)}</div><Table rows={movements.filter(m=>m.account===selected&&matches(m.date,period,year))} edit={m=>{setEditing(m);setModal('movement')}} detailed/></div></section>}
{page==='cards'&&<section className="content"><div className="toolbar"><div><h2>Cartões de crédito</h2><p>Valor das compras conforme o filtro selecionado.</p></div></div><div className="account-grid">{accounts.map(a=>{const total=purchases.filter(p=>p.account===a.id&&matches(p.date,period,year)).reduce((s,p)=>s+p.value,0);return <div className="credit-card" key={a.id}><div><CreditCard/><span>{a.name}</span></div><small>{a.cardName}</small><strong>{money(total)}</strong><span>Fatura no período: {period}</span></div>})}</div></section>}
{page==='receipts'&&<section className="content"><div className="empty-state"><div className="empty-icon"><FileText/></div><h2>Comprovantes</h2><p>Os comprovantes são anexados diretamente às movimentações.</p><button className="secondary" onClick={()=>go('movements')}><Eye size={15}/> Ir para movimentações</button></div></section>}
{page==='users'&&<section className="content"><div className="empty-state"><div className="empty-icon"><Users/></div><h2>Usuários e permissões</h2><p>Área reservada ao gerenciamento de usuários e permissões.</p></div></section>}{page==='settings'&&<section className="content"><div className="empty-state"><div className="empty-icon"><Settings/></div><h2>Configurações</h2><p>Configurações da aplicação.</p></div></section>}
{modal==='account'&&<Modal title="Nova conta" close={()=>setModal(null)}><form onSubmit={saveAccount}><label>Nome da conta<input name="name" required placeholder="Ex.: Conta Principal"/></label><label>Banco<input name="bank" required placeholder="Ex.: Santander"/></label><label>Saldo atual<input name="balance" type="number" step="0.01" defaultValue="0"/></label><label>Nome do cartão<input name="cardName" placeholder="Ex.: Cartão Principal"/></label><Actions cancel={()=>setModal(null)} text="Criar conta"/></form></Modal>}
{modal==='movement'&&<Modal title={editing?'Editar movimentação':'Nova movimentação'} close={()=>{setModal(null);setEditing(null)}}><form onSubmit={saveMovement}><label>Conta<select name="account" defaultValue={editing?.account||selected}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Data<input name="date" type="date" defaultValue={editing?.date||'2026-09-14'} required/></label><label>Tipo<select name="type" defaultValue={editing?.type||'Entrada'}><option>Entrada</option><option>Saída</option></select></label><label>Valor<input name="value" type="number" step="0.01" defaultValue={editing?.value||''} required/></label><label>Descrição<input name="description" defaultValue={editing?.description||''} required/></label><label>Referência<input name="reference" defaultValue={editing?.reference||''} required/></label><label>Comprovante<input name="receipt" type="file" accept="image/*,.pdf"/></label>{editing?.receipt&&<div className="current-receipt"><Paperclip size={15}/> Comprovante atual: <b>{editing.receipt.name}</b></div>}<Actions cancel={()=>{setModal(null);setEditing(null)}} text={editing?'Salvar alterações':'Salvar movimentação'}/></form></Modal>}
{confirm&&<div className="modal-bg"><div className="confirm-modal"><div className="danger-icon"><Trash2/></div><h2>Excluir conta?</h2><p>Tem certeza que deseja excluir <b>{confirm.name}</b>?</p><p>As movimentações vinculadas a esta conta também serão removidas.</p><Actions cancel={()=>setConfirm(null)} danger text="Sim, excluir" ok={()=>removeAccount(confirm.id)}/></div></div>}
{notice&&<div className="toast">{notice}</div>}</main></div>}
function Table({rows,edit,detailed}){return <div className="table-wrap"><table><thead><tr><th>Data</th>{detailed&&<th>Tipo</th>}<th>Movimentação</th><th>Referência</th>{detailed&&<th>Comprovante</th>}<th>Valor</th><th>Ação</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{dateBR(m.date)}</td>{detailed&&<td>{m.type}</td>}<td><span className={m.type==='Entrada'?'movement in':'movement out'}>{m.type==='Entrada'?<ArrowDownLeft size={14}/>:<ArrowUpRight size={14}/>} {m.description}</span></td><td>{m.reference}</td>{detailed&&<td>{m.receipt?<span className="receipt-badge"><Paperclip size={13}/>{m.receipt.name}</span>:<span className="muted">Não anexado</span>}</td>}<td className={m.type==='Entrada'?'positive':'negative'}>{m.type==='Entrada'?'+':'-'} {money(m.value)}</td><td><button className="table-action" title="Editar movimentação" onClick={()=>edit(m)}><Pencil size={15}/></button></td></tr>)}{!rows.length&&<tr><td className="empty-row" colSpan={detailed?7:5}>Nenhuma movimentação no período.</td></tr>}</tbody></table></div>}
function Modal({title,close,children}){return <div className="modal-bg" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{title}</h2><p>Preencha os dados e salve.</p></div><button className="icon" onClick={close}><X/></button></div>{children}</div></div>}
function Actions({cancel,text,danger,ok}){return <div className="modal-actions"><button type="button" className="secondary" onClick={cancel}>Cancelar</button><button type={ok?'button':'submit'} className={danger?'danger solid':'primary'} onClick={ok}>{text}</button></div>}
createRoot(document.getElementById('root')).render(<App/>)
